package cn.sxh.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.sxh.greendao.TechnologyTable;

import cn.sxh.greendao.TechnologyTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig technologyTableDaoConfig;

    private final TechnologyTableDao technologyTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        technologyTableDaoConfig = daoConfigMap.get(TechnologyTableDao.class).clone();
        technologyTableDaoConfig.initIdentityScope(type);

        technologyTableDao = new TechnologyTableDao(technologyTableDaoConfig, this);

        registerDao(TechnologyTable.class, technologyTableDao);
    }
    
    public void clear() {
        technologyTableDaoConfig.getIdentityScope().clear();
    }

    public TechnologyTableDao getTechnologyTableDao() {
        return technologyTableDao;
    }

}
