package cn.sxh.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TECHNOLOGY_TABLE".
 */
@Entity
public class TechnologyTable {

    @Id
    @NotNull
    @Index
    private String SnowFoxChannelName;

    @NotNull
    private String SnowFoxChannelId;

    @NotNull
    private String SnowFoxChannelType;

    @Generated
    public TechnologyTable() {
    }

    public TechnologyTable(String SnowFoxChannelName) {
        this.SnowFoxChannelName = SnowFoxChannelName;
    }

    @Generated
    public TechnologyTable(String SnowFoxChannelName, String SnowFoxChannelId, String SnowFoxChannelType) {
        this.SnowFoxChannelName = SnowFoxChannelName;
        this.SnowFoxChannelId = SnowFoxChannelId;
        this.SnowFoxChannelType = SnowFoxChannelType;
    }

    @NotNull
    public String getSnowFoxChannelName() {
        return SnowFoxChannelName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSnowFoxChannelName(@NotNull String SnowFoxChannelName) {
        this.SnowFoxChannelName = SnowFoxChannelName;
    }

    @NotNull
    public String getSnowFoxChannelId() {
        return SnowFoxChannelId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSnowFoxChannelId(@NotNull String SnowFoxChannelId) {
        this.SnowFoxChannelId = SnowFoxChannelId;
    }

    @NotNull
    public String getSnowFoxChannelType() {
        return SnowFoxChannelType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSnowFoxChannelType(@NotNull String SnowFoxChannelType) {
        this.SnowFoxChannelType = SnowFoxChannelType;
    }

}
