package cn.sxh.snow.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SNOW_FOX_TABLE".
 */
@Entity
public class SnowFoxTable {

    @Id
    @NotNull
    @Index
    private String SnowFoxChannelName;

    @NotNull
    private String SnowFoxChannelId;

    @NotNull
    private String SnowFoxChannelType;
    private boolean SnowFoxChannelSelect;
    private int SnowFoxChannelIndex;
    private Boolean SnowFoxChannelFixed;

    @Generated
    public SnowFoxTable() {
    }

    public SnowFoxTable(String SnowFoxChannelName) {
        this.SnowFoxChannelName = SnowFoxChannelName;
    }

    @Generated
    public SnowFoxTable(String SnowFoxChannelName, String SnowFoxChannelId, String SnowFoxChannelType, boolean SnowFoxChannelSelect, int SnowFoxChannelIndex, Boolean SnowFoxChannelFixed) {
        this.SnowFoxChannelName = SnowFoxChannelName;
        this.SnowFoxChannelId = SnowFoxChannelId;
        this.SnowFoxChannelType = SnowFoxChannelType;
        this.SnowFoxChannelSelect = SnowFoxChannelSelect;
        this.SnowFoxChannelIndex = SnowFoxChannelIndex;
        this.SnowFoxChannelFixed = SnowFoxChannelFixed;
    }

    @NotNull
    public String getSnowFoxChannelName() {
        return SnowFoxChannelName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSnowFoxChannelName(@NotNull String SnowFoxChannelName) {
        this.SnowFoxChannelName = SnowFoxChannelName;
    }

    @NotNull
    public String getSnowFoxChannelId() {
        return SnowFoxChannelId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSnowFoxChannelId(@NotNull String SnowFoxChannelId) {
        this.SnowFoxChannelId = SnowFoxChannelId;
    }

    @NotNull
    public String getSnowFoxChannelType() {
        return SnowFoxChannelType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSnowFoxChannelType(@NotNull String SnowFoxChannelType) {
        this.SnowFoxChannelType = SnowFoxChannelType;
    }

    public boolean getSnowFoxChannelSelect() {
        return SnowFoxChannelSelect;
    }

    public void setSnowFoxChannelSelect(boolean SnowFoxChannelSelect) {
        this.SnowFoxChannelSelect = SnowFoxChannelSelect;
    }

    public int getSnowFoxChannelIndex() {
        return SnowFoxChannelIndex;
    }

    public void setSnowFoxChannelIndex(int SnowFoxChannelIndex) {
        this.SnowFoxChannelIndex = SnowFoxChannelIndex;
    }

    public Boolean getSnowFoxChannelFixed() {
        return SnowFoxChannelFixed;
    }

    public void setSnowFoxChannelFixed(Boolean SnowFoxChannelFixed) {
        this.SnowFoxChannelFixed = SnowFoxChannelFixed;
    }

}
